### ISSUE TITLE
Fix to avoid error when bigfoot.js is compressed/minified

### ISSUE THREAD

**Issue by brunob** [lemonmade/bigfoot#28]
Hi @lemonmade here is a fix to avoid error when unminified version of the script is minified with an external tool :

https://github.com/lemonmade/bigfoot/blob/master/dist/bigfoot.js#L32

`footnoteButtonSearchQuery = settings.scope ? "" + settings.scope + " a[href*=\"#\"]" : "a[href*=\"#\"]";`

should be replaced with :

`footnoteButtonSearchQuery = settings.scope ? '' + settings.scope + ' a[href*="#"]' : 'a[href*="#"]';`

(like it's done in min version of the script)

**Comment by brunob** [comment]
Any news about this @lemonmade ?

**Comment by lemonmade** [comment]
Sorry for never replying to this. This issue is in the dist version of the script, which is compiled automatically from the CoffeeScript source. Since I have no control over that compilation, I lean towards not making any changes for this.

**Comment by brunob** [comment]
Thx for anwsering :) Sad that this can't be fixed, maybe we need to open a issue on CoffeeScript side ?

**Comment by lemonmade** [comment]
Can you see if the most recent version in this repo fixes the issue? I went to single quotes inside double quoted strings, which I think should resolve the minifier warnings.

**Comment by brunob** [comment]
(y) well done @lemonmade :)
