### ISSUE TITLE
Can't scroll popover until window is resized in Safari on El Capitan

### ISSUE THREAD

**Issue by zcohan** [lemonmade/bigfoot#48]
Popovers with overflow content will not scroll until the window is resized in Safari (only on El Capitan  – it works fine in Chrome on El Capitan, and in Safari on Yosemite).

It's reproducible on the demo page (use the footnote button under "Usage" for example). Just open the page, then click the footnote to open the popover. 2-finger scrolling the popover should fail. Resize the window with the popover still visible, and 2 finger scrolling the popover should now work.

Note that closing and reopening the popover requires the window again be resized for scrolling to work.

Example movie showing the problem here:
http://cl.ly/dRBS

**Comment by lemonmade** [comment]
Confirmed that this is an issue — I will try to take a look this weekend.

**Comment by CalebGrove** [comment]
This bug seems to have fixed itself in one of the recent El Capitan releases.

**Comment by zcohan** [comment]
True!
