### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by keiron77** [lemonmade/bigfoot#52]
Can it be applied to links with a particular class without using rel with dynamically sourced content in the tooltip? I am thinking something like clicking a link with a class 'define' which then opens the footnote with dynamically sourced content based on the text found in the define link:

JS:
```
$('.define').bigfoot({
content: $("h3:contains('"+$(this).text()+"')" ).next('p').text();
});
```

HTML:

```
<a href="#" class="define">Information</a>
<h3>Information</h3>
<p>Footnote copy</p>
```

**Comment by lemonmade** [comment]
I understand the desire for this, but I feel like it's too far out from the core purpose of this tool. This particular tool is really for dropping onto a typical blog post and having it just make things better, not a generalizable utility for tooltips.

**Comment by keiron77** [comment]
Thanks Chris,

No worries. I managed to get it working how I wanted using your API. I noticed one mistake in your api for buttonMarkup (although the functional JS is correct):

<div class="bigfoot-footnote__container">
  <button href="#" class="bigfoot-footnote__button" rel="footnote"
     id="{{SUP:data-footnote-backlink-ref}}"
     data-footnote-number="{{FOOTNOTENUM}}"
     data-footnote-identifier="{{FOOTNOTEID}}"
     alt="See Footnote {{FOOTNOTENUM}}"
     data-footnote-content="{{FOOTNOTECONTENT}}">

     <svg class="bigfoot-footnote__button__circle" viewbox="0 0 6 6" preserveAspectRatio="xMinYMin"><circle r="3" cx="3" cy="3" fill="white"></circle></svg>
     <svg class="bigfoot-footnote__button__circle" viewbox="0 0 6 6" preserveAspectRatio="xMinYMin"><circle r="3" cx="3" cy="3" fill="white"></circle></svg>
     <svg class="bigfoot-footnote__button__circle" viewbox="0 0 6 6" preserveAspectRatio="xMinYMin"><circle r="3" cx="3" cy="3" fill="white"></circle></svg>
     
  </button>
</div>

should be:

<div class="bigfoot-footnote__container">
  <button href="#" class="bigfoot-footnote__button" rel="footnote"
     id="{{SUP:data-footnote-backlink-ref}}"
     data-footnote-number="{{FOOTNOTENUM}}"
     data-footnote-identifier="{{FOOTNOTEID}}"
     alt="See Footnote {{FOOTNOTENUM}}"
     data-bigfoot-footnote="{{FOOTNOTECONTENT}}">

     <svg class="bigfoot-footnote__button__circle" viewbox="0 0 6 6" preserveAspectRatio="xMinYMin"><circle r="3" cx="3" cy="3" fill="white"></circle></svg>
     <svg class="bigfoot-footnote__button__circle" viewbox="0 0 6 6" preserveAspectRatio="xMinYMin"><circle r="3" cx="3" cy="3" fill="white"></circle></svg>
     <svg class="bigfoot-footnote__button__circle" viewbox="0 0 6 6" preserveAspectRatio="xMinYMin"><circle r="3" cx="3" cy="3" fill="white"></circle></svg>
     
  </button>
</div>



Best regards,

Keiron




 

Keiron Roberts 

e: keiron@jerram.co.uk <mailto:keiron@jerram.co.uk>
m: +44 (0)7740 190 913
t: +44 (0)845 003 7246
skype: keironroberts
jerram.com <http://www.jerram.com/>

 <http://www.linkedin.com/company/jerram>  <http://www.linkedin.com/company/jerram> <http://twitter.com/JerramCulture/>
 <http://twitter.com/JerramCulture/>


/culture  <http://www.jerram.co.uk/culture/category/company>| /keiron <http://www.jerram.co.uk/culture/keiron>
Jerram Marketing Ltd. | Atlantic House | Imperial Way | Reading | RG2 0TD

Disclaimer
The information in this e-mail and any attached files is confidential. If you are not the named recipient, or have otherwise received this communication in error, please delete it from your inbox, notify the sender immediately, and do not disclose its contents to any other person, use it for any purpose, or store or copy the information in any medium. The views of the author may not necessarily reflect those of the company.
Please note that neither Jerram Marketing Limited nor the sender accepts any responsibility for viruses and it is your responsibility to scan this message and any attachments. 
Jerram Marketing Limited | Registered in England & Wales No. 5932754 | Registered office: 5 South Parade, Summertown, Oxford. OX2 7JL
