### ISSUE TITLE
Footnotes are much narrower than they are on bigfoot.js

### ISSUE THREAD

**Issue by Jackmc1047** [lemonmade/bigfoot#55]
@lemonmade 
My footnotes are very narrow when activated and also clip their content. How can I make them wider, like they are on bigfootjs.com? I have the code below. Thanks in advance. 

    <section>
        <article>
            <p>
                text text text<sup><a href="#fn:1" rel="footnote"></a></sup> text text text
            </p>
            <div class="footnotes">
                <ol>
                    <li class="footnote" id="fn:1">
                        <p>footnote text</p>
                    </li>
                </ol>
            </div>
        </article>
    </section>

**Comment by lukasschwab** [comment]
Hi! Let me guess, you're using jQuery 3.x?

I think you're experiencing the same problem I ran into: https://github.com/lemonmade/bigfoot/issues/54

As described on that issue, I fixed the problem by using an earlier version of jQuery (1.8.3).

**Comment by Jackmc1047** [comment]
Thanks for the info. I see you did previously mention this issue. Sorry I missed it.
